// Ignore this script, everyone.

const LPWSTR = "pointer";
const LPRECT = "pointer";
const LPPOINT = "pointer";
const autoitFunctions = {
  AU3_Init: ["void", []],
  AU3_error: ["int", []],
  AU3_AutoItSetOption: ["int", ["string16", "int"]],
  AU3_ClipGet: ["void", [LPWSTR, "int"]],
  AU3_ClipPut: ["void", ["string16"]],
  AU3_ControlClick: [
    "int",
    ["string16", "string16", "string16", "string16", "int", "int", "int"],
  ],
  AU3_ControlClickByHandle: [
    "int",
    ["int", "int", "string16", "int", "int", "int"],
  ],
  AU3_ControlCommand: [
    "void",
    ["string16", "string16", "string16", "string16", "string16", LPWSTR, "int"],
  ],
  AU3_ControlCommandByHandle: [
    "void",
    ["int", "int", "string16", "string16", LPWSTR, "int"],
  ],
  AU3_ControlListView: [
    "void",
    [
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      LPWSTR,
      "int",
    ],
  ],
  AU3_ControlListViewByHandle: [
    "void",
    ["int", "int", "string16", "string16", "string16", LPWSTR, "int"],
  ],
  AU3_ControlDisable: ["int", ["string16", "string16", "string16"]],
  AU3_ControlDisableByHandle: ["int", ["int", "int"]],
  AU3_ControlEnable: ["int", ["string16", "string16", "string16"]],
  AU3_ControlEnableByHandle: ["int", ["int", "int"]],
  AU3_ControlFocus: ["int", ["string16", "string16", "string16"]],
  AU3_ControlFocusByHandle: ["int", ["int", "int"]],
  AU3_ControlGetFocus: ["void", ["string16", "string16", LPWSTR, "int"]],
  AU3_ControlGetFocusByHandle: ["void", ["int", LPWSTR, "int"]],
  AU3_ControlGetHandle: ["int", ["int", "string16"]],
  AU3_ControlGetHandleAsText: [
    "void",
    [
      "string16",
      /*[in,defaultvalue("")]*/ "string16",
      "string16",
      LPWSTR,
      "int",
    ],
  ],
  AU3_ControlGetPos: ["int", ["string16", "string16", "string16", LPRECT]],
  AU3_ControlGetPosByHandle: ["int", ["int", "int", LPRECT]],
  AU3_ControlGetText: [
    "void",
    ["string16", "string16", "string16", LPWSTR, "int"],
  ],
  AU3_ControlGetTextByHandle: ["void", ["int", "int", LPWSTR, "int"]],
  AU3_ControlHide: ["int", ["string16", "string16", "string16"]],
  AU3_ControlHideByHandle: ["int", ["int", "int"]],
  AU3_ControlMove: [
    "int",
    ["string16", "string16", "string16", "int", "int", "int", "int"],
  ],
  AU3_ControlMoveByHandle: ["int", ["int", "int", "int", "int", "int", "int"]],
  AU3_ControlSend: [
    "int",
    ["string16", "string16", "string16", "string16", "int"],
  ],
  AU3_ControlSendByHandle: ["int", ["int", "int", "string16", "int"]],
  AU3_ControlSetText: ["int", ["string16", "string16", "string16", "string16"]],
  AU3_ControlSetTextByHandle: ["int", ["int", "int", "string16"]],
  AU3_ControlShow: ["int", ["string16", "string16", "string16"]],
  AU3_ControlShowByHandle: ["int", ["int", "int"]],
  AU3_ControlTreeView: [
    "void",
    [
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      LPWSTR,
      "int",
    ],
  ],
  AU3_ControlTreeViewByHandle: [
    "void",
    ["int", "int", "string16", "string16", "string16", LPWSTR, "int"],
  ],
  AU3_DriveMapAdd: [
    "void",
    [
      "string16",
      "string16",
      "int",
      /*[in,defaultvalue("")]*/ "string16",
      /*[in,defaultvalue("")]*/ "string16",
      LPWSTR,
      "int",
    ],
  ],
  AU3_DriveMapDel: ["int", ["string16"]],
  AU3_DriveMapGet: ["void", ["string16", LPWSTR, "int"]],
  AU3_IsAdmin: ["int", []],
  AU3_MouseClick: [
    "int",
    [/*[in,defaultvalue("LEFT")]*/ "string16", "int", "int", "int", "int"],
  ],
  AU3_MouseClickDrag: ["int", ["string16", "int", "int", "int", "int", "int"]],
  AU3_MouseDown: ["void", [/*[in,defaultvalue("LEFT")]*/ "string16"]],
  AU3_MouseGetCursor: ["int", []],
  AU3_MouseGetPos: ["void", [LPPOINT]],
  AU3_MouseMove: ["int", ["int", "int", "int"]],
  AU3_MouseUp: ["void", [/*[in,defaultvalue("LEFT")]*/ "string16"]],
  AU3_MouseWheel: ["void", ["string16", "int"]],
  AU3_Opt: ["int", ["string16", "int"]],
  AU3_PixelChecksum: ["uint", [LPRECT, "int"]],
  AU3_PixelGetColor: ["int", ["int", "int"]],
  AU3_PixelSearch: [
    "void",
    [LPRECT, "int", /*default 0*/ "int", /*default 1*/ "int", LPPOINT],
  ],
  AU3_ProcessClose: ["int", ["string16"]],
  AU3_ProcessExists: ["int", ["string16"]],
  AU3_ProcessSetPriority: ["int", ["string16", "int"]],
  AU3_ProcessWait: ["int", ["string16", "int"]],
  AU3_ProcessWaitClose: ["int", ["string16", "int"]],
  AU3_Run: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16", "int"]],
  AU3_RunWait: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_RunAs: [
    "int",
    [
      "string16",
      "string16",
      "string16",
      "int",
      "string16",
      /*[in,defaultvalue("")]*/ "string16",
      "int",
    ],
  ],
  AU3_RunAsWait: [
    "int",
    [
      "string16",
      "string16",
      "string16",
      "int",
      "string16",
      /*[in,defaultvalue("")]*/ "string16",
      "int",
    ],
  ],
  AU3_Send: ["void", ["string16", "int"]],
  AU3_Shutdown: ["int", ["int"]],
  AU3_Sleep: ["void", ["int"]],
  AU3_StatusbarGetText: [
    "int",
    [
      "string16",
      /*[in,defaultvalue("")]*/ "string16",
      /*[in,defaultvalue(1)]*/ "int",
      LPWSTR,
      "int",
    ],
  ],
  AU3_StatusbarGetTextByHandle: [
    "int",
    ["int", /*[in,defaultvalue(1)]*/ "int", LPWSTR, "int"],
  ],
  AU3_ToolTip: ["void", ["string16", "int", "int"]],
  AU3_WinActivate: ["int", ["string16", "string16"]],
  AU3_WinActivateByHandle: ["int", ["int"]],
  AU3_WinActive: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16"]],
  AU3_WinActiveByHandle: ["int", ["int"]],
  AU3_WinClose: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16"]],
  AU3_WinCloseByHandle: ["int", ["int"]],
  AU3_WinExists: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16"]],
  AU3_WinExistsByHandle: ["int", ["int"]],
  AU3_WinGetCaretPos: ["int", [LPPOINT]],
  AU3_WinGetClassList: [
    "void",
    ["string16", /*[in,defaultvalue("")]*/ "string16", LPWSTR, "int"],
  ],
  AU3_WinGetClassListByHandle: ["void", ["int", LPWSTR, "int"]],
  AU3_WinGetClientSize: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", LPRECT],
  ],
  AU3_WinGetClientSizeByHandle: ["int", ["int", LPRECT]],
  AU3_WinGetHandle: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16"]],
  AU3_WinGetHandleAsText: [
    "void",
    ["string16", /*[in,defaultvalue("")]*/ "string16", LPWSTR, "int"],
  ],
  AU3_WinGetPos: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", LPRECT],
  ],
  AU3_WinGetPosByHandle: ["int", ["int", LPRECT]],
  AU3_WinGetProcess: [
    "uint32",
    ["string16", /*[in,defaultvalue("")]*/ "string16"],
  ],
  AU3_WinGetProcessByHandle: ["uint32", ["int"]],
  AU3_WinGetState: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16"]],
  AU3_WinGetStateByHandle: ["int", ["int"]],
  AU3_WinGetText: [
    "void",
    ["string16", /*[in,defaultvalue("")]*/ "string16", LPWSTR, "int"],
  ],
  AU3_WinGetTextByHandle: ["void", ["int", LPWSTR, "int"]],
  AU3_WinGetTitle: [
    "void",
    ["string16", /*[in,defaultvalue("")]*/ "string16", LPWSTR, "int"],
  ],
  AU3_WinGetTitleByHandle: ["void", ["int", LPWSTR, "int"]],
  AU3_WinKill: ["int", ["string16", /*[in,defaultvalue("")]*/ "string16"]],
  AU3_WinKillByHandle: ["int", ["int"]],
  AU3_WinMenuSelectItem: [
    "int",
    [
      "string16",
      /*[in,defaultvalue("")]*/ "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
    ],
  ],
  AU3_WinMenuSelectItemByHandle: [
    "int",
    [
      "int",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
      "string16",
    ],
  ],
  AU3_WinMinimizeAll: ["void", []],
  AU3_WinMinimizeAllUndo: ["void", []],
  AU3_WinMove: [
    "int",
    [
      "string16",
      /*[in,defaultvalue("")]*/ "string16",
      "int",
      "int",
      "int",
      "int",
    ],
  ],
  AU3_WinMoveByHandle: ["int", ["int", "int", "int", "int", "int"]],
  AU3_WinSetOnTop: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_WinSetOnTopByHandle: ["int", ["int", "int"]],
  AU3_WinSetState: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_WinSetStateByHandle: ["int", ["int", "int"]],
  AU3_WinSetTitle: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "string16"],
  ],
  AU3_WinSetTitleByHandle: ["int", ["int", "string16"]],
  AU3_WinSetTrans: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_WinSetTransByHandle: ["int", ["int", "int"]],
  AU3_WinWait: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_WinWaitByHandle: ["int", ["int", "int"]],
  AU3_WinWaitActive: ["int", ["string16", "string16", "int"]],
  AU3_WinWaitActiveByHandle: ["int", ["int", "int"]],
  AU3_WinWaitClose: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_WinWaitCloseByHandle: ["int", ["int", "int"]],
  AU3_WinWaitNotActive: [
    "int",
    ["string16", /*[in,defaultvalue("")]*/ "string16", "int"],
  ],
  AU3_WinWaitNotActiveByHandle: ["int", ["int", "int"]],
};
